from spire.xls import *
from spire.xls.common import *


outputFile = "CreatePivotTable.xlsx"

workbook = Workbook()
sheet = workbook.Worksheets[0]
# Set the value to the cells
sheet.Range["A1"].Value = "Product"
sheet.Range["B1"].Value = "Month"
sheet.Range["C1"].Value = "Count"
sheet.Range["A2"].Value = "SpireDoc"
sheet.Range["A3"].Value = "SpireDoc"
sheet.Range["A4"].Value = "SpireXls"
sheet.Range["A5"].Value = "SpireDoc"
sheet.Range["A6"].Value = "SpireXls"
sheet.Range["A7"].Value = "SpireXls"
sheet.Range["B2"].Value = "January"
sheet.Range["B3"].Value = "February"
sheet.Range["B4"].Value = "January"
sheet.Range["B5"].Value = "January"
sheet.Range["B6"].Value = "February"
sheet.Range["B7"].Value = "February"
sheet.Range["C2"].Value = "10"
sheet.Range["C3"].Value = "15"
sheet.Range["C4"].Value = "9"
sheet.Range["C5"].Value = "7"
sheet.Range["C6"].Value = "8"
sheet.Range["C7"].Value = "10"
#Add a PivotTable to the worksheet
dataRange = sheet.Range["A1:C7"]
cache = workbook.PivotCaches.Add(dataRange)
pt = sheet.PivotTables.Add("Pivot Table", sheet.Range["E10"], cache)
#Drag the fields to the row area.
pf = pt.PivotFields["Product"]
pf.Axis = AxisTypes.Row
pf2 = pt.PivotFields["Month"]
pf2.Axis = AxisTypes.Row
#Drag the field to the data area.
pt.DataFields.Add(pt.PivotFields["Count"], "SUM of Count", SubtotalTypes.Sum)
#Set PivotTable style
pt.BuiltInStyle = PivotBuiltInStyles.PivotStyleMedium12
#Autofit columns generated by the pivotTable
pt.CalculateData()
sheet.AutoFitColumn(5)
sheet.AutoFitColumn(6)
workbook.SaveToFile(outputFile, ExcelVersion.Version2010)
workbook.Dispose()

